### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Kibishan** [Androz2091/simsimi-bot#2]
(Sorry for m’y English, I am French)
Hello I have a problem : when I do " /chat hello " the bot react with 😢 
How can I fix it ?

**Comment by Androz2091** [comment]
Hello,
This happened because the Simsimi API didn't return a valid response. Did you fill the "Simsimi API Key" field in the configuration file?

**Comment by Kibishan** [comment]
Yes but it is the trial version

**Comment by Androz2091** [comment]
You need to have a valid key. To get it, you'll have to provide a credit card to Simsimi.

**Comment by Kibishan** [comment]
Ok merci

**Comment by Kibishan** [comment]
Thanks*

**Comment by starghoost** [comment]
I have the api but it only answers me 😢

**Comment by Androz2091** [comment]
Do you have any error?

**Comment by Androz2091** [comment]
Closed due to inactivity.
